version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/project

jobs:
  build:
    executor: java-executor
    steps:
      - checkout

      # Cache dependencies to speed up builds
      - restore_cache:
          keys:
            - maven-cache-{{ checksum "pom.xml" }}
            - maven-cache

      # Install dependencies
      - run:
          name: Install dependencies
          command: mvn dependency:resolve dependency:resolve-plugins

      # Save dependencies to cache
      - save_cache:
          paths:
            - ~/.m2
          key: maven-cache-{{ checksum "pom.xml" }}

      # Run tests
      - run:
          name: Run tests
          command: mvn test

      # Build the application
      - run:
          name: Build application
          command: mvn clean package

      # Save artifacts (e.g., JAR file)
      - store_artifacts:
          path: target
          destination: build-artifacts

      # Upload test results
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
